sudo: required
services: 
  - docker

before_install:
  - docker build -t tintuntint/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true tintuntint/react-test npm test

after_success:
    - docker build -t tintuntint/multi-client ./client
    - docker build -t tintuntint/multi-nginx ./nginx
    - docker build -t tintuntint/multi-server ./server
    - docker build -t tintuntint/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tintuntint/multi-client
    - docker push tintuntint/multi-nginx
    - docker push tintuntint/multi-server
    - docker push tintuntint/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-ap-southeast-2-519900252451"
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY    


